# Generated by Django 3.2.4 on 2021-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('added_date', models.DateField()),
                ('cost_price', models.IntegerField()),
                ('marked_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('buyed_party', models.CharField(max_length=200)),
                ('extra_information', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sold_product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('added_date', models.DateField()),
                ('sold_date', models.DateField()),
                ('cost_price', models.IntegerField()),
                ('marked_price', models.IntegerField()),
                ('sold_price', models.IntegerField()),
                ('buyed_party', models.CharField(max_length=200)),
                ('sold_party', models.CharField(max_length=200)),
                ('extra_information', models.TextField(null=True)),
            ],
        ),
    ]
