# Generated by Django 3.2.4 on 2021-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sold_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_product',
            name='extra_information',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sold_product',
            name='extra_information',
            field=models.TextField(default=''),
        ),
    ]
